name: Generate CV Files

on:
  push:
    branch: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install --save-dev
      - run: npm run validate
      - run: npm run generate cv.pdf
      - run: npm run generate cv.html
      - uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: cv.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: cv.html
          path: cv.html
